---

- name: Install python2-pip and setuptools for ansible
  become: true
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - python-pip
    - python-setuptools

- name: Install enchant
  become: true
  package:
    name: enchant
    state: present

- name: Add universe repository for ubuntu
  become: true
  apt_repository:
    repo: >-
        deb http://archive.ubuntu.com/ubuntu
        {{ ansible_distribution_release|lower }} universe
    state: present
  when:
    - ansible_distribution == 'Ubuntu'

- name: Install sopel RedHat
  become: true
  pip:
    name: sopel
    executable: pip3.6
  when: ansible_os_family == 'RedHat'

- name: Install sopel Debian
  become: true
  environment:
    LC_ALL: en_US.UTF-8
  pip:
    name: sopel
    executable: pip3
  when: ansible_os_family == 'Debian'

- name: Add sopel system user
  become: true
  user:
    name: sopel
    password: '!'
    home: '{{ sopel_install_dir }}'
    system: true
    state: present

- name: Make sopel folders
  become: true
  file:
    path: '{{ item }}'
    owner: sopel
    group: sopel
    state: directory
  with_items:
    - '{{ sopel_config_dir }}'
    - '{{ sopel_log_dir }}'
    - '{{ sopel_pid_dir }}'

- name: Copy sopel config
  become: true
  template:
    owner: sopel
    group: sopel
    src: templates/sopel.cfg.j2
    dest: '{{ sopel_config_dir }}/sopel.cfg'

- name: Add sopel systemd service
  become: true
  template:
    owner: sopel
    group: sopel
    src: templates/sopel.service.j2
    dest: /etc/systemd/system/sopel.service
  when: sopel_install_systemd_service

- name: Start and enable sopel
  become: true
  service:
    name: sopel
    state: started
    enabled: true
  when: sopel_install_systemd_service
