---
- name: Add universe repository for ubuntu
  become: true
  apt_repository:
    repo: >-
        deb http://archive.ubuntu.com/ubuntu
        {{ ansible_distribution_release|lower }} universe
    state: present
  when:
    - ansible_distribution == 'Ubuntu'

- name: Add sopel system user
  become: true
  user:
    name: sopel
    password: '!'
    home: '{{ sopel_install_dir }}'
    system: true
    state: present

- name: Make sopel folders
  become: true
  file:
    path: '{{ item }}'
    owner: sopel
    group: sopel
    mode: 0744
    state: directory
  with_items:
    - '{{ sopel_config_dir }}'
    - '{{ sopel_log_dir }}'
    - '{{ sopel_log_dir }}/{{ sopel_instance_name }}'
    - '{{ sopel_pid_dir }}'

- name: Copy sopel config
  become: true
  template:
    owner: sopel
    group: sopel
    mode: 0644
    src: templates/sopel.cfg.j2
    dest: '{{ sopel_config_dir }}/{{ sopel_instance_name }}.cfg'
  notify: restart sopel

- name: Add sopel systemd service
  become: true
  template:
    owner: root
    group: root
    mode: 0644
    src: templates/sopel.service.j2
    dest: /etc/systemd/system/sopel-{{ sopel_instance_name }}.service
  notify: restart sopel
  when: sopel_install_systemd_service|bool

- name: Install sopel
  environment:
    LC_ALL: 'en_US.UTF-8'
  pip:
    name: [pip>19, setuptools>40, sopel>7]
    state: present
    virtualenv: '{{ sopel_install_dir }}/venv_{{ sopel_instance_name }}'
    virtualenv_command: '{{ sopel_venv_cmd }}'
  notify: restart sopel

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  when: ansible_service_mgr == "systemd"

- name: Enable sopel systemd service
  become: true
  service:
    name: 'sopel-{{ sopel_instance_name }}'
    enabled: true
  when: sopel_install_systemd_service|bool
