---
- name: Converge
  hosts: all
  become: true
  vars:
    sopel_auth_method: 'nickserv'
    sopel_bot_owner: 'testman'
    sopel_auth_user: authUser
    sopel_auth_pass: authPass
    sopel_start_systemd_service: false

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Ensure python3 is installed
      package:
        name: python3

    - name: Ensure virtualenv and wheel is available (Debian)
      package:
        name:
          - python3-venv
          - python3-wheel
      when: ansible_os_family == 'Debian'

    - name: Ensure wheel is available (Rhel)
      package:
        name:
          - python-wheel

    - name: Wait for systemd to complete initialization.  # noqa 303
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

  roles:
    - role: sopel.sopel
