---
- name: Converge
  hosts: all
  vars:
    sopel_auth_method: 'nickserv'
    sopel_bot_owner: 'testman'
    sopel_auth_user: authUser
    sopel_auth_pass: authPass
    sopel_start_systemd_service: false

  pre_tasks:
    - name: Ensure apt is updated
      apt:
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: "Include sopel.sopel"
      include_role:
        name: "sopel.sopel"
