---
- name: Converge
  hosts: all

  vars:
    sopel_auth_method: 'nickserv'
    sopel_bot_owner: 'testman'
    sopel_auth_user: authUser
    sopel_auth_pass: authPass

  pre_tasks:
    - name: Ensure apt is updated
      apt:
        update_cache: true
      when: ansible_os_family == 'Debian'

  roles:
    - role: sopel.sopel
