---
- name: Converge
  hosts: all

  tasks:
    - name: Upgrade all packages (Debian)
      apt:
        upgrade: dist
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: upgrade all packages (RedHat)
      yum:
        name: '*'
        state: latest
        update_cache: true
      when: ansible_os_family == 'RedHat'
